### ISSUE TITLE
Combined with Uppy.js Tus post-test feedback

### ISSUE THREAD

**Issue by netnr** [Newex/solidTUS#2]
- `OnUploadFinished` is not executed
- Example of content returned after upload is complete
- During the upload process, calling the Delete method to delete files is not supported
- Hope to add `MetaDirectoryPath` parameter in `StartCreationAsync` method

**Comment by Newex** [comment]
Hey thanks for the feedback!

I'll look into this issue, but is has been a while since I wrote this code.

**Comment by Newex** [comment]
> **OnUploadFinished is not executed**

I've found that if `OnUploadFinished` is defined after starting the upload process `StartCreationAsync` (if the file is using the TUS extension [Creation-With-Upload](https://tus.io/protocols/resumable-upload#creation-with-upload)) or using the "regular" protocol `StartAppendDataAsync` the callback will not be called.

There are multiple solutions here:

Simplest is to reorder the code, example:

```csharp
context.OnUploadFinished( /* callback */);
await context.StartAppendDataAsync(fileId);
```

Another could be to not await when starting the upload:

```csharp
// not await
var upload = context.StartAppendDataAsync(fileId);
context.OnUploadFinished( /* callback */);
...
await upload;
```

The third is probably more complex. I could try to create some fluent api over the `Context`.

> **Example of content returned after upload is complete**

I don't understand, I just try to follow TUS specs.

> **During the upload process, calling the Delete method to delete files is not supported**

Yeah, I have not implemented the [Termination-Extension](https://tus.io/protocols/resumable-upload#termination). I'll update the readme to show which extra extensions that are currently supported. And i'll try to build those in the future.

> **Hope to add MetaDirectoryPath parameter in StartCreationAsync method**

Ok, will add issue.

**Comment by netnr** [comment]
> Example of content returned after upload is complete

I learned that the TUS protocol returns a 204 status code when the Patch is completed. If you want to obtain the file information, you need to initiate a separate HEAD request based on the Location parameter.

My initial thought was to also return the content when Patch completes

**Comment by Newex** [comment]
The http method 204 should not have any content in the body. Also if I deviate from spec then other libraries will find this behavior unexpected.

**Comment by netnr** [comment]
`<PackageReference Include="SolidTUS" Version="0.0.18" />`

I tried it and rolled back to the previous version.

The Patch request TusUpload method did not write data and was repeated many times.
swagger error message `Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0`

**Comment by Newex** [comment]
I don't think that is a problem with SolidTus but how you have defined routes maybe.

Remember you have to have unique routes to each action. Which is differentiated by the http method + the url.  
If you have 1 route that can map to 2 or more different actions then the routes you have chosen are ambiguous.

I found this StackOverflow answer: https://stackoverflow.com/a/62963918/1640121

I tried browsing the swagger schema in the the [dotnetcore example project](https://github.com/Newex/solidTUS/tree/main/examples/dotnetcore) and had no problems. I also tried to upload and had no problems.

I have added simple example using [uppy/tus - here](https://github.com/Newex/solidTUS/tree/main/examples/sveltedotnet).

Anyways I have just released v.0.0.19 which can now terminate uploads, see the examples or read the documentation or wiki.

Hope this helps and let me know how it goes.
